// Code generated by entc, DO NOT EDIT.

package party

const (
	// Label holds the string label denoting the party type in the database.
	Label = "party"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// Table holds the table name of the party in the database.
	Table = "parties"
)

// Columns holds all SQL columns for party fields.
var Columns = []string{
	FieldID,
	FieldChannelID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
