// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LootsColumns holds the columns for the "loots" table.
	LootsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"D1", "D2", "D3", "D4", "MT", "ST", "H1", "H2"}},
	}
	// LootsTable holds the schema information for the "loots" table.
	LootsTable = &schema.Table{
		Name:       "loots",
		Columns:    LootsColumns,
		PrimaryKey: []*schema.Column{LootsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LootsTable,
	}
)

func init() {
}
