// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/KawashiroNitori/lootbot/ent/migrate"

	"github.com/KawashiroNitori/lootbot/ent/loot"
	"github.com/KawashiroNitori/lootbot/ent/party"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Loot is the client for interacting with the Loot builders.
	Loot *LootClient
	// Party is the client for interacting with the Party builders.
	Party *PartyClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Loot = NewLootClient(c.config)
	c.Party = NewPartyClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Loot:   NewLootClient(cfg),
		Party:  NewPartyClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Loot:   NewLootClient(cfg),
		Party:  NewPartyClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Loot.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Loot.Use(hooks...)
	c.Party.Use(hooks...)
}

// LootClient is a client for the Loot schema.
type LootClient struct {
	config
}

// NewLootClient returns a client for the Loot from the given config.
func NewLootClient(c config) *LootClient {
	return &LootClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `loot.Hooks(f(g(h())))`.
func (c *LootClient) Use(hooks ...Hook) {
	c.hooks.Loot = append(c.hooks.Loot, hooks...)
}

// Create returns a create builder for Loot.
func (c *LootClient) Create() *LootCreate {
	mutation := newLootMutation(c.config, OpCreate)
	return &LootCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Loot entities.
func (c *LootClient) CreateBulk(builders ...*LootCreate) *LootCreateBulk {
	return &LootCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Loot.
func (c *LootClient) Update() *LootUpdate {
	mutation := newLootMutation(c.config, OpUpdate)
	return &LootUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LootClient) UpdateOne(l *Loot) *LootUpdateOne {
	mutation := newLootMutation(c.config, OpUpdateOne, withLoot(l))
	return &LootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LootClient) UpdateOneID(id int64) *LootUpdateOne {
	mutation := newLootMutation(c.config, OpUpdateOne, withLootID(id))
	return &LootUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Loot.
func (c *LootClient) Delete() *LootDelete {
	mutation := newLootMutation(c.config, OpDelete)
	return &LootDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LootClient) DeleteOne(l *Loot) *LootDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LootClient) DeleteOneID(id int64) *LootDeleteOne {
	builder := c.Delete().Where(loot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LootDeleteOne{builder}
}

// Query returns a query builder for Loot.
func (c *LootClient) Query() *LootQuery {
	return &LootQuery{
		config: c.config,
	}
}

// Get returns a Loot entity by its id.
func (c *LootClient) Get(ctx context.Context, id int64) (*Loot, error) {
	return c.Query().Where(loot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LootClient) GetX(ctx context.Context, id int64) *Loot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LootClient) Hooks() []Hook {
	return c.hooks.Loot
}

// PartyClient is a client for the Party schema.
type PartyClient struct {
	config
}

// NewPartyClient returns a client for the Party from the given config.
func NewPartyClient(c config) *PartyClient {
	return &PartyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `party.Hooks(f(g(h())))`.
func (c *PartyClient) Use(hooks ...Hook) {
	c.hooks.Party = append(c.hooks.Party, hooks...)
}

// Create returns a create builder for Party.
func (c *PartyClient) Create() *PartyCreate {
	mutation := newPartyMutation(c.config, OpCreate)
	return &PartyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Party entities.
func (c *PartyClient) CreateBulk(builders ...*PartyCreate) *PartyCreateBulk {
	return &PartyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Party.
func (c *PartyClient) Update() *PartyUpdate {
	mutation := newPartyMutation(c.config, OpUpdate)
	return &PartyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PartyClient) UpdateOne(pa *Party) *PartyUpdateOne {
	mutation := newPartyMutation(c.config, OpUpdateOne, withParty(pa))
	return &PartyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PartyClient) UpdateOneID(id string) *PartyUpdateOne {
	mutation := newPartyMutation(c.config, OpUpdateOne, withPartyID(id))
	return &PartyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Party.
func (c *PartyClient) Delete() *PartyDelete {
	mutation := newPartyMutation(c.config, OpDelete)
	return &PartyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *PartyClient) DeleteOne(pa *Party) *PartyDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *PartyClient) DeleteOneID(id string) *PartyDeleteOne {
	builder := c.Delete().Where(party.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PartyDeleteOne{builder}
}

// Query returns a query builder for Party.
func (c *PartyClient) Query() *PartyQuery {
	return &PartyQuery{
		config: c.config,
	}
}

// Get returns a Party entity by its id.
func (c *PartyClient) Get(ctx context.Context, id string) (*Party, error) {
	return c.Query().Where(party.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PartyClient) GetX(ctx context.Context, id string) *Party {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PartyClient) Hooks() []Hook {
	return c.hooks.Party
}
