// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/KawashiroNitori/lootbot/ent/loot"
	"github.com/KawashiroNitori/lootbot/internal/macro"
)

// Loot is the model entity for the Loot schema.
type Loot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Role holds the value of the "role" field.
	Role macro.Role `json:"role,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Loot) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case loot.FieldRole:
			values[i] = new(macro.Role)
		case loot.FieldID:
			values[i] = new(sql.NullInt64)
		case loot.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Loot", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Loot fields.
func (l *Loot) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int64(value.Int64)
		case loot.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				l.Name = value.String
			}
		case loot.FieldRole:
			if value, ok := values[i].(*macro.Role); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value != nil {
				l.Role = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Loot.
// Note that you need to call Loot.Unwrap() before calling this method if this Loot
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Loot) Update() *LootUpdateOne {
	return (&LootClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Loot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Loot) Unwrap() *Loot {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Loot is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Loot) String() string {
	var builder strings.Builder
	builder.WriteString("Loot(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", name=")
	builder.WriteString(l.Name)
	builder.WriteString(", role=")
	builder.WriteString(fmt.Sprintf("%v", l.Role))
	builder.WriteByte(')')
	return builder.String()
}

// Loots is a parsable slice of Loot.
type Loots []*Loot

func (l Loots) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
