// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/KawashiroNitori/lootbot/ent/loot"
	"github.com/KawashiroNitori/lootbot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lootFields := schema.Loot{}.Fields()
	_ = lootFields
	// lootDescName is the schema descriptor for name field.
	lootDescName := lootFields[1].Descriptor()
	// loot.NameValidator is a validator for the "name" field. It is called by the builders before save.
	loot.NameValidator = lootDescName.Validators[0].(func(string) error)
}
