// Code generated by "enumer -type Role -trimprefix Role -transform upper -sql -output role_string.go"; DO NOT EDIT.

package macro

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _RoleName = "D1D2D3D4MTSTH1H2"

var _RoleIndex = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16}

const _RoleLowerName = "d1d2d3d4mtsth1h2"

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i+1)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[RoleD1-(1)]
	_ = x[RoleD2-(2)]
	_ = x[RoleD3-(3)]
	_ = x[RoleD4-(4)]
	_ = x[RoleMT-(5)]
	_ = x[RoleST-(6)]
	_ = x[RoleH1-(7)]
	_ = x[RoleH2-(8)]
}

var _RoleValues = []Role{RoleD1, RoleD2, RoleD3, RoleD4, RoleMT, RoleST, RoleH1, RoleH2}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:2]:        RoleD1,
	_RoleLowerName[0:2]:   RoleD1,
	_RoleName[2:4]:        RoleD2,
	_RoleLowerName[2:4]:   RoleD2,
	_RoleName[4:6]:        RoleD3,
	_RoleLowerName[4:6]:   RoleD3,
	_RoleName[6:8]:        RoleD4,
	_RoleLowerName[6:8]:   RoleD4,
	_RoleName[8:10]:       RoleMT,
	_RoleLowerName[8:10]:  RoleMT,
	_RoleName[10:12]:      RoleST,
	_RoleLowerName[10:12]: RoleST,
	_RoleName[12:14]:      RoleH1,
	_RoleLowerName[12:14]: RoleH1,
	_RoleName[14:16]:      RoleH2,
	_RoleLowerName[14:16]: RoleH2,
}

var _RoleNames = []string{
	_RoleName[0:2],
	_RoleName[2:4],
	_RoleName[4:6],
	_RoleName[6:8],
	_RoleName[8:10],
	_RoleName[10:12],
	_RoleName[12:14],
	_RoleName[14:16],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i Role) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Role) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Role: %[1]T(%[1]v)", value)
	}

	val, err := RoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
