// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Loot is the predicate function for loot builders.
type Loot func(*sql.Selector)

// Party is the predicate function for party builders.
type Party func(*sql.Selector)
